[package]
authors = ["Radim Janoš <radim.janos@apitree.cz>"]
edition = "2018"
name = "agent-tag"
repository = "https://github.com/janos-r/agent-tag"
version = "0.1.0"

[dependencies]
rand = "0.8"
structopt = "0.3"
