[package]
authors = ["Radim Janoš <radim.janos@apitree.cz>"]
edition = "2018"
name = "agent-tag"
repository = "https://github.com/janos-r/agent-tag"
version = "0.1.0"

[dependencies]
rand = {version = "0.8", features = ["small_rng"]}
rayon = "1.5"
structopt = "0.3"
